problems:
- goal:
    robot_0: state_1
    robot_1: state_0
    robot_2: state_3
    robot_3: state_4
    robot_4: state_5
    robot_5: state_2
    robot_6: state_7
    robot_7: state_8
    robot_8: state_9
    robot_9: state_6
  name: problem
  start:
    robot_0: state_0
    robot_1: state_1
    robot_2: state_2
    robot_3: state_3
    robot_4: state_4
    robot_5: state_5
    robot_6: state_6
    robot_7: state_7
    robot_8: state_8
    robot_9: state_9
roadmaps:
- name: roadmap
  states:
  - name: state_0
    to:
    - state_1
    - state_0
    - state_9
    - state_10
    x: 10.0
    y: 0.0
    z: 0
  - name: state_1
    to:
    - state_2
    - state_1
    - state_0
    - state_11
    x: 8.090169943749475
    y: 5.877852522924732
    z: 0
  - name: state_2
    to:
    - state_3
    - state_2
    - state_1
    - state_12
    x: 3.0901699437494745
    y: 9.510565162951535
    z: 0
  - name: state_3
    to:
    - state_4
    - state_3
    - state_2
    - state_13
    x: -3.0901699437494736
    y: 9.510565162951536
    z: 0
  - name: state_4
    to:
    - state_5
    - state_4
    - state_3
    - state_14
    x: -8.090169943749473
    y: 5.877852522924733
    z: 0
  - name: state_5
    to:
    - state_6
    - state_5
    - state_4
    - state_15
    x: -10.0
    y: 1.2246467991473533e-15
    z: 0
  - name: state_6
    to:
    - state_7
    - state_6
    - state_5
    - state_16
    x: -8.090169943749476
    y: -5.87785252292473
    z: 0
  - name: state_7
    to:
    - state_8
    - state_7
    - state_6
    - state_17
    x: -3.0901699437494754
    y: -9.510565162951535
    z: 0
  - name: state_8
    to:
    - state_9
    - state_8
    - state_7
    - state_18
    x: 3.0901699437494723
    y: -9.510565162951536
    z: 0
  - name: state_9
    to:
    - state_0
    - state_9
    - state_8
    - state_19
    x: 8.090169943749473
    y: -5.877852522924734
    z: 0
  - name: state_10
    to:
    - state_1
    - state_10
    - state_9
    - state_0
    x: 10.0
    y: 0.0
    z: 5
  - name: state_11
    to:
    - state_2
    - state_11
    - state_0
    - state_1
    x: 8.090169943749475
    y: 5.877852522924732
    z: 5
  - name: state_12
    to:
    - state_3
    - state_12
    - state_1
    - state_2
    x: 3.0901699437494745
    y: 9.510565162951535
    z: 5
  - name: state_13
    to:
    - state_4
    - state_13
    - state_2
    - state_3
    x: -3.0901699437494736
    y: 9.510565162951536
    z: 5
  - name: state_14
    to:
    - state_5
    - state_14
    - state_3
    - state_4
    x: -8.090169943749473
    y: 5.877852522924733
    z: 5
  - name: state_15
    to:
    - state_6
    - state_15
    - state_4
    - state_5
    x: -10.0
    y: 1.2246467991473533e-15
    z: 5
  - name: state_16
    to:
    - state_7
    - state_16
    - state_5
    - state_6
    x: -8.090169943749476
    y: -5.87785252292473
    z: 5
  - name: state_17
    to:
    - state_8
    - state_17
    - state_6
    - state_7
    x: -3.0901699437494754
    y: -9.510565162951535
    z: 5
  - name: state_18
    to:
    - state_9
    - state_18
    - state_7
    - state_8
    x: 3.0901699437494723
    y: -9.510565162951536
    z: 5
  - name: state_19
    to:
    - state_0
    - state_19
    - state_8
    - state_9
    x: 8.090169943749473
    y: -5.877852522924734
    z: 5
  type: drone
robots:
- name: robot_0
  roadmap: roadmap
  type: drone
- name: robot_1
  roadmap: roadmap
  type: drone
- name: robot_2
  roadmap: roadmap
  type: drone
- name: robot_3
  roadmap: roadmap
  type: drone
- name: robot_4
  roadmap: roadmap
  type: drone
- name: robot_5
  roadmap: roadmap
  type: drone
- name: robot_6
  roadmap: roadmap
  type: drone
- name: robot_7
  roadmap: roadmap
  type: drone
- name: robot_8
  roadmap: roadmap
  type: drone
- name: robot_9
  roadmap: roadmap
  type: drone
voxels:
  type: PCL_GPU
