problems:
    - goal:
          robot_0: state_1
          robot_1: state_2
          robot_2: state_3
          robot_3: state_4
          robot_4: state_5
          robot_5: state_6
          robot_6: state_7
          robot_7: state_8
          robot_8: state_9
          robot_9: state_0
      name: problem
      start:
          robot_0: state_0
          robot_1: state_1
          robot_2: state_2
          robot_3: state_3
          robot_4: state_4
          robot_5: state_5
          robot_6: state_6
          robot_7: state_7
          robot_8: state_8
          robot_9: state_9
roadmaps:
    - name: roadmap
      states:
          - name: state_0
            x: 5.0
            y: 0.0
            z: 0
          - name: state_1
            x: 4.045084971874737
            y: 2.938926261462366
            z: 0
          - name: state_2
            x: 1.5450849718747373
            y: 4.755282581475767
            z: 0
          - name: state_3
            x: -1.5450849718747368
            y: 4.755282581475768
            z: 0
          - name: state_4
            x: -4.045084971874736
            y: 2.9389262614623664
            z: 0
          - name: state_5
            x: -5.0
            y: 6.123233995736766e-16
            z: 0
          - name: state_6
            x: -4.045084971874738
            y: -2.938926261462365
            z: 0
          - name: state_7
            x: -1.5450849718747377
            y: -4.755282581475767
            z: 0
          - name: state_8
            x: 1.5450849718747361
            y: -4.755282581475768
            z: 0
          - name: state_9
            x: 4.045084971874736
            y: -2.938926261462367
            z: 0
      type: drone
robots:
    - name: robot_0
      roadmap: roadmap
      type: drone
    - name: robot_1
      roadmap: roadmap
      type: drone
    - name: robot_2
      roadmap: roadmap
      type: drone
    - name: robot_3
      roadmap: roadmap
      type: drone
    - name: robot_4
      roadmap: roadmap
      type: drone
    - name: robot_5
      roadmap: roadmap
      type: drone
    - name: robot_6
      roadmap: roadmap
      type: drone
    - name: robot_7
      roadmap: roadmap
      type: drone
    - name: robot_8
      roadmap: roadmap
      type: drone
    - name: robot_9
      roadmap: roadmap
      type: drone
voxels:
    type: PCL
